### ISSUE TITLE
urllib2.HTTPError and ValueError

### ISSUE THREAD

**Issue by noraj1337** [aepereyra/lfimap#3]
(As I said in my mail), I installed lfimap from [Black Arch repository](https://blackarch.org/tools.html) and when I tested it I got those bugs:

```
$ lfimap --target="https://mindreader.web.ctfcompetition.com/?f=/etc/passwd"
Traceback (most recent call last):
  File "lfimap.py", line 384, in <module>
    urlt= autodetect (url, us, pw, prox)
  File "lfimap.py", line 51, in autodetect
    handle = urllib2.urlopen(x)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: NOT FOUND

$ lfimap --target="https://mindreader.web.ctfcompetition.com/"
Traceback (most recent call last):
  File "lfimap.py", line 384, in <module>
    urlt= autodetect (url, us, pw, prox)
  File "lfimap.py", line 15, in autodetect
    params = dict([part.split('=') for part in url[4].split('&')])
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

`HTTP Error 404: NOT FOUND` is surprising because the website was up and running.

**Comment by noraj1337** [comment]
Note : answer in the mail was 

> Use the official repository

But official repository in just a tarball with not install steps and dependencies...

**Comment by aepereyra** [comment]
Sorry the ctf is finished but i think the script fails because the parser detect also the file extention of the vulnerable file: example http://www.tetst.com/**vulnerablefile.php**?vulnparameter=xxxxxx
That what you test hasn't got the name of the vulnerable file only the parameter    https://mindreader.web.ctfcompetition.com/?f=/etc/passwd"
I need to add support to this kind of site sorry
